<div class="login-container">
    <?php if($block->is2faConfiguredForCustomer()): ?>
    <div class="block block-customer-login" style="width: 100%">
        <div class="block-content">
            <p><?php echo __('Two-Factor Authentication already configured. Contact support if you wish to reset it.'); ?></p>
        </div>
    </div>
    <?php else: ?>
    <img src="<?php /* @escapeNotVerified */ echo $block->getQrCodeBase64Image(); ?>" alt="2FA Authenticator">
    <div class="block block-customer-login" style="width: 48%">
        <p><?php echo __('Download a 2FA app on your phone to scan the QR code and get the authentication code, for example Google Authenticator or Authy.'); ?></p>
        <div class="block-content">
            <form class="form contact" action="<?php /* @escapeNotVerified */ echo $block->getSetupFormAction(); ?>" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <input type="hidden" name="secret" value="<?php /* @escapeNotVerified */ echo $block->getSecretCode(); ?>" />
                <fieldset class="fieldset">
                    <div class="field name required">
                        <label class="label" for="code"><span><?php /* @escapeNotVerified */ echo __('Authentication Code') ?></span></label>
                        <div class="control">
                            <input name="code" id="code" title="<?php /* @escapeNotVerified */ echo __('Authentication Code') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">

                    <div class="primary">
                        <button class="primary" title="<?php /* @escapeNotVerified */ echo __('Cancel') ?>" class="action primary">
                            <a href="/customer/account">
                                <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                            </a>
                        </button>
                    </div>

                    <div class="primary">
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Authenticate') ?>" class="action submit primary">
                            <span><?php /* @escapeNotVerified */ echo __('Authenticate') ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php endif; ?>
</div>
